### POST AUTHEmpresas
POST http://localhost:8097/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ademir:testo

### GET Empresas
GET http://localhost:8097/loginEmpresa

### add Empresas
POST http://localhost:8097/loginEmpresa/cadastrar
Content-Type: application/json

{
  "login": "2@a",
  "password": "22"
}

### GET vagas
GET http://localhost:8097/vagasEmpresa
